// Ergo-L layout key definitions for ZMK
// Generated from ergol.json
#pragma once

#define EL_Q &kp KeyQ
#define EL_C &kp KeyW
#define EL_O &kp KeyE
#define EL_P &kp KeyR
#define EL_W &kp KeyT
#define EL_J &kp KeyY
#define EL_M &kp KeyU
#define EL_D &kp KeyI
#define EL_TYPO &kp KeyO
#define EL_Y &kp KeyP
#define EL_A &kp KeyA
#define EL_S &kp KeyS
#define EL_E &kp KeyD
#define EL_N &kp KeyF
#define EL_F &kp KeyG
#define EL_L &kp KeyH
#define EL_R &kp KeyJ
#define EL_T &kp KeyK
#define EL_I &kp KeyL
#define EL_U &kp Semicolon
#define EL_Z &kp KeyZ
#define EL_X &kp KeyX
#define EL_MINUS &kp KeyC
#define EL_V &kp KeyV
#define EL_B &kp KeyB
#define EL_DOT &kp KeyN
#define EL_H &kp KeyM
#define EL_G &kp Comma
#define EL_COMMA &kp Period
#define EL_K &kp Slash
#define EL_1 &kp Digit1
#define EL_2 &kp Digit2
#define EL_3 &kp Digit3
#define EL_4 &kp Digit4
#define EL_5 &kp Digit5
#define EL_6 &kp Digit6
#define EL_7 &kp Digit7
#define EL_8 &kp Digit8
#define EL_9 &kp Digit9
#define EL_0 &kp Digit0
#define EL_SLASH &kp Minus
#define EL_EQ &kp Equal
#define EL_LBRACK &kp BracketLeft
#define EL_RBRACK &kp BracketRight
#define EL_SQUO &kp Quote
#define EL_GRAVE &kp Backquote
#define EL_BSLASH &kp Backslash
#define EL_LT &kp IntlBackslash